package com.wy.dao;

import com.wy.model.BaiduPoi;
import java.util.List;

public interface BaiduPoiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_poi
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	int deleteByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_poi
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	int insert(BaiduPoi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_poi
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	BaiduPoi selectByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_poi
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	List<BaiduPoi> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_poi
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	int updateByPrimaryKey(BaiduPoi record);
}