package com.wy.dao;

import com.wy.model.InviteInfo;
import java.util.List;

public interface InviteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invite_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invite_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int insert(InviteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invite_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    InviteInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invite_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    List<InviteInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invite_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int updateByPrimaryKey(InviteInfo record);
}