package com.wy.dao;

import com.wy.model.JoinInfo;
import java.util.List;

public interface JoinInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_join_info
	 * @mbggenerated  Mon Jul 27 13:46:06 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);
	int deleteByInviteId(JoinInfo record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_join_info
	 * @mbggenerated  Mon Jul 27 13:46:06 CST 2015
	 */
	int insert(JoinInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_join_info
	 * @mbggenerated  Mon Jul 27 13:46:06 CST 2015
	 */
	JoinInfo selectByPrimaryKey(Integer id);
	JoinInfo selectMySignInfo(JoinInfo record);
	JoinInfo selectByInviteId(Integer inviteId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_join_info
	 * @mbggenerated  Mon Jul 27 13:46:06 CST 2015
	 */
	List<JoinInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_join_info
	 * @mbggenerated  Mon Jul 27 13:46:06 CST 2015
	 */
	int updateByPrimaryKey(JoinInfo record);
}