package com.wy.dao;

import com.wy.model.JoinInfo;
import java.util.List;

public interface JoinInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_join_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_join_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int insert(JoinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_join_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    JoinInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_join_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    List<JoinInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_join_info
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    int updateByPrimaryKey(JoinInfo record);
}