package com.wy.dao;

import com.wy.model.JsapiTicket;
import java.util.List;

public interface JsapiTicketMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_jsapi_ticket
	 * @mbggenerated  Fri Jun 26 11:03:33 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_jsapi_ticket
	 * @mbggenerated  Fri Jun 26 11:03:33 CST 2015
	 */
	int insert(JsapiTicket record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_jsapi_ticket
	 * @mbggenerated  Fri Jun 26 11:03:33 CST 2015
	 */
	JsapiTicket selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_jsapi_ticket
	 * @mbggenerated  Fri Jun 26 11:03:33 CST 2015
	 */
	List<JsapiTicket> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_jsapi_ticket
	 * @mbggenerated  Fri Jun 26 11:03:33 CST 2015
	 */
	int updateByPrimaryKey(JsapiTicket record);
}