package com.wy.dao;

import com.wy.model.News;

import java.util.List;
import java.util.Map;

public interface NewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated  Tue May 12 13:26:23 CST 2015
	 */
	int deleteByPrimaryKey(Integer newsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated  Tue May 12 13:26:23 CST 2015
	 */
	int insert(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated  Tue May 12 13:26:23 CST 2015
	 */
	News selectByPrimaryKey(Integer newsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated  Tue May 12 13:26:23 CST 2015
	 */
	List<News> selectAll(Map map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated  Tue May 12 13:26:23 CST 2015
	 */
	int updateByPrimaryKey(News record);

	int updatePublish(News record);
	
	int updateTop(News record);
	
	int updateDelete(News record);
	
	List<News> selectAllByType(Integer typeId);
	
	int selectTotal(Map map);
}