package com.wy.dao;

import com.wy.model.News;
import com.wy.model.NewsFile;

import java.util.List;

public interface NewsFileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_file
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	int deleteByPrimaryKey(Integer fileId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_file
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	int insert(NewsFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_file
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	NewsFile selectByPrimaryKey(Integer fileId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_file
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	List<NewsFile> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_file
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	int updateByPrimaryKey(NewsFile record);
	
	int deleteByNewsId(Integer newsId);
	
	List<NewsFile> selectByNewsId(Integer newsId);
}