package com.wy.dao;

import com.wy.model.NewsType;
import java.util.List;

public interface NewsTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_type
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	int deleteByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_type
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	int insert(NewsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_type
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	NewsType selectByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_type
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	List<NewsType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news_type
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	int updateByPrimaryKey(NewsType record);
	
	List<NewsType> selectAllEnable();
}