package com.wy.dao;

import com.wy.model.Picture;
import java.util.List;

public interface PictureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	int deleteByPrimaryKey(Integer picId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	int insert(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	Picture selectByPrimaryKey(Integer picId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	List<Picture> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_picture
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	int updateByPrimaryKey(Picture record);
}