package com.wy.dao;

import com.wy.model.SysParam;
import java.util.List;

public interface SysParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    int deleteByPrimaryKey(Integer sysParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    int insert(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    SysParam selectByPrimaryKey(String sysParamName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    List<SysParam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    int updateByPrimaryKey(SysParam record);
}