package com.wy.dao;

import com.wy.model.WeixinUser;
import java.util.List;

public interface WeixinUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbggenerated Wed Jun 24 09:25:31 CST 2015
     */
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbggenerated Wed Jun 24 09:25:31 CST 2015
     */
    int insert(WeixinUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbggenerated Wed Jun 24 09:25:31 CST 2015
     */
    WeixinUser selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbggenerated Wed Jun 24 09:25:31 CST 2015
     */
    List<WeixinUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbggenerated Wed Jun 24 09:25:31 CST 2015
     */
    int updateByPrimaryKey(WeixinUser record);
}