package com.wy.model;

import java.util.Date;

public class AccessToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_access_token.id
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_access_token.expires_in
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	private Integer expiresIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_access_token.access_expires
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	private Long accessExpires;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_access_token.access_expiresCH
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	private Date accessExpiresch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_access_token.access_token
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	private String accessToken;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_access_token.id
	 * @return  the value of t_access_token.id
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_access_token.id
	 * @param id  the value for t_access_token.id
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_access_token.expires_in
	 * @return  the value of t_access_token.expires_in
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public Integer getExpiresIn() {
		return expiresIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_access_token.expires_in
	 * @param expiresIn  the value for t_access_token.expires_in
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public void setExpiresIn(Integer expiresIn) {
		this.expiresIn = expiresIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_access_token.access_expires
	 * @return  the value of t_access_token.access_expires
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public Long getAccessExpires() {
		return accessExpires;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_access_token.access_expires
	 * @param accessExpires  the value for t_access_token.access_expires
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public void setAccessExpires(Long accessExpires) {
		this.accessExpires = accessExpires;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_access_token.access_expiresCH
	 * @return  the value of t_access_token.access_expiresCH
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public Date getAccessExpiresch() {
		return accessExpiresch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_access_token.access_expiresCH
	 * @param accessExpiresch  the value for t_access_token.access_expiresCH
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public void setAccessExpiresch(Date accessExpiresch) {
		this.accessExpiresch = accessExpiresch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_access_token.access_token
	 * @return  the value of t_access_token.access_token
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public String getAccessToken() {
		return accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_access_token.access_token
	 * @param accessToken  the value for t_access_token.access_token
	 * @mbggenerated  Tue Jun 23 13:46:01 CST 2015
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}
}