package com.wy.model;

public class BaiduPoi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.id
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.lat
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.lng
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float lng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.price
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.overall_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float overallRating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.taste_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float tasteRating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.service_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float serviceRating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.environment_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Float environmentRating;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.image_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Integer imageNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.comment_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private Integer commentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.uid
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.name
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.address
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.tag
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.detail_url
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String detailUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.type
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.shop_hours
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String shopHours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.atmosphere
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String atmosphere;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.featured_service
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String featuredService;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_poi.description
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.id
	 * @return  the value of t_poi.id
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.id
	 * @param id  the value for t_poi.id
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.lat
	 * @return  the value of t_poi.lat
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.lat
	 * @param lat  the value for t_poi.lat
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setLat(Float lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.lng
	 * @return  the value of t_poi.lng
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getLng() {
		return lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.lng
	 * @param lng  the value for t_poi.lng
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setLng(Float lng) {
		this.lng = lng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.price
	 * @return  the value of t_poi.price
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.price
	 * @param price  the value for t_poi.price
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.overall_rating
	 * @return  the value of t_poi.overall_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getOverallRating() {
		return overallRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.overall_rating
	 * @param overallRating  the value for t_poi.overall_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setOverallRating(Float overallRating) {
		this.overallRating = overallRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.taste_rating
	 * @return  the value of t_poi.taste_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getTasteRating() {
		return tasteRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.taste_rating
	 * @param tasteRating  the value for t_poi.taste_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setTasteRating(Float tasteRating) {
		this.tasteRating = tasteRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.service_rating
	 * @return  the value of t_poi.service_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getServiceRating() {
		return serviceRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.service_rating
	 * @param serviceRating  the value for t_poi.service_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setServiceRating(Float serviceRating) {
		this.serviceRating = serviceRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.environment_rating
	 * @return  the value of t_poi.environment_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Float getEnvironmentRating() {
		return environmentRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.environment_rating
	 * @param environmentRating  the value for t_poi.environment_rating
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setEnvironmentRating(Float environmentRating) {
		this.environmentRating = environmentRating;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.image_num
	 * @return  the value of t_poi.image_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Integer getImageNum() {
		return imageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.image_num
	 * @param imageNum  the value for t_poi.image_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setImageNum(Integer imageNum) {
		this.imageNum = imageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.comment_num
	 * @return  the value of t_poi.comment_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public Integer getCommentNum() {
		return commentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.comment_num
	 * @param commentNum  the value for t_poi.comment_num
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setCommentNum(Integer commentNum) {
		this.commentNum = commentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.uid
	 * @return  the value of t_poi.uid
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.uid
	 * @param uid  the value for t_poi.uid
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.name
	 * @return  the value of t_poi.name
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.name
	 * @param name  the value for t_poi.name
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.address
	 * @return  the value of t_poi.address
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.address
	 * @param address  the value for t_poi.address
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.tag
	 * @return  the value of t_poi.tag
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.tag
	 * @param tag  the value for t_poi.tag
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.detail_url
	 * @return  the value of t_poi.detail_url
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getDetailUrl() {
		return detailUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.detail_url
	 * @param detailUrl  the value for t_poi.detail_url
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setDetailUrl(String detailUrl) {
		this.detailUrl = detailUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.type
	 * @return  the value of t_poi.type
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.type
	 * @param type  the value for t_poi.type
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.shop_hours
	 * @return  the value of t_poi.shop_hours
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getShopHours() {
		return shopHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.shop_hours
	 * @param shopHours  the value for t_poi.shop_hours
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setShopHours(String shopHours) {
		this.shopHours = shopHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.atmosphere
	 * @return  the value of t_poi.atmosphere
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getAtmosphere() {
		return atmosphere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.atmosphere
	 * @param atmosphere  the value for t_poi.atmosphere
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setAtmosphere(String atmosphere) {
		this.atmosphere = atmosphere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.featured_service
	 * @return  the value of t_poi.featured_service
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getFeaturedService() {
		return featuredService;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.featured_service
	 * @param featuredService  the value for t_poi.featured_service
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setFeaturedService(String featuredService) {
		this.featuredService = featuredService;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_poi.description
	 * @return  the value of t_poi.description
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_poi.description
	 * @param description  the value for t_poi.description
	 * @mbggenerated  Fri Sep 25 11:47:07 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_poi.int
     *
     * @mbggenerated Fri Sep 25 11:46:35 CST 2015
     */

    
}