package com.wy.model;

public class JoinInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_join_info.id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_join_info.open_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_join_info.invite_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    private Integer inviteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_join_info.id
     *
     * @return the value of t_join_info.id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_join_info.id
     *
     * @param id the value for t_join_info.id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_join_info.open_id
     *
     * @return the value of t_join_info.open_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_join_info.open_id
     *
     * @param openId the value for t_join_info.open_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_join_info.invite_id
     *
     * @return the value of t_join_info.invite_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public Integer getInviteId() {
        return inviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_join_info.invite_id
     *
     * @param inviteId the value for t_join_info.invite_id
     *
     * @mbggenerated Mon Jun 29 11:27:27 CST 2015
     */
    public void setInviteId(Integer inviteId) {
        this.inviteId = inviteId;
    }
}