package com.wy.model;

public class NewsType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_type.type_id
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_type.type_name
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_type.type_no
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	private Integer typeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_type.enable
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	private Integer enable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_type.type_id
	 * @return  the value of t_news_type.type_id
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_type.type_id
	 * @param typeId  the value for t_news_type.type_id
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_type.type_name
	 * @return  the value of t_news_type.type_name
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_type.type_name
	 * @param typeName  the value for t_news_type.type_name
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_type.type_no
	 * @return  the value of t_news_type.type_no
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public Integer getTypeNo() {
		return typeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_type.type_no
	 * @param typeNo  the value for t_news_type.type_no
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public void setTypeNo(Integer typeNo) {
		this.typeNo = typeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_type.enable
	 * @return  the value of t_news_type.enable
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public Integer getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_type.enable
	 * @param enable  the value for t_news_type.enable
	 * @mbggenerated  Wed May 13 10:53:15 CST 2015
	 */
	public void setEnable(Integer enable) {
		this.enable = enable;
	}
}