package com.wy.model;

public class NewsFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_file.file_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	private Integer fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_file.file_name
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_file.file_path
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	private String filePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_file.type_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news_file.news_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	private Integer newsId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_file.file_id
	 * @return  the value of t_news_file.file_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_file.file_id
	 * @param fileId  the value for t_news_file.file_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_file.file_name
	 * @return  the value of t_news_file.file_name
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_file.file_name
	 * @param fileName  the value for t_news_file.file_name
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_file.file_path
	 * @return  the value of t_news_file.file_path
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public String getFilePath() {
		return filePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_file.file_path
	 * @param filePath  the value for t_news_file.file_path
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_file.type_id
	 * @return  the value of t_news_file.type_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_file.type_id
	 * @param typeId  the value for t_news_file.type_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news_file.news_id
	 * @return  the value of t_news_file.news_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public Integer getNewsId() {
		return newsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news_file.news_id
	 * @param newsId  the value for t_news_file.news_id
	 * @mbggenerated  Tue May 12 11:21:56 CST 2015
	 */
	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}
}