package com.wy.model;

public class Picture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.pic_id
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	private Integer picId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.pic_title
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	private String picTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.pic_name
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	private String picName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.pic_path
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	private String picPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_picture.pic_order
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	private Integer picOrder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.pic_id
	 * @return  the value of t_picture.pic_id
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public Integer getPicId() {
		return picId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.pic_id
	 * @param picId  the value for t_picture.pic_id
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public void setPicId(Integer picId) {
		this.picId = picId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.pic_title
	 * @return  the value of t_picture.pic_title
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public String getPicTitle() {
		return picTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.pic_title
	 * @param picTitle  the value for t_picture.pic_title
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public void setPicTitle(String picTitle) {
		this.picTitle = picTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.pic_name
	 * @return  the value of t_picture.pic_name
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public String getPicName() {
		return picName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.pic_name
	 * @param picName  the value for t_picture.pic_name
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public void setPicName(String picName) {
		this.picName = picName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.pic_path
	 * @return  the value of t_picture.pic_path
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public String getPicPath() {
		return picPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.pic_path
	 * @param picPath  the value for t_picture.pic_path
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public void setPicPath(String picPath) {
		this.picPath = picPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_picture.pic_order
	 * @return  the value of t_picture.pic_order
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public Integer getPicOrder() {
		return picOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_picture.pic_order
	 * @param picOrder  the value for t_picture.pic_order
	 * @mbggenerated  Tue May 19 12:50:20 CST 2015
	 */
	public void setPicOrder(Integer picOrder) {
		this.picOrder = picOrder;
	}
}