package com.wy.model;

public class SysParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_param.sys_param_id
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    private Integer sysParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_param.sys_param_name
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    private String sysParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_param.sys_param_value
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    private String sysParamValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_param.sys_param_id
     *
     * @return the value of t_sys_param.sys_param_id
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public Integer getSysParamId() {
        return sysParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_param.sys_param_id
     *
     * @param sysParamId the value for t_sys_param.sys_param_id
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public void setSysParamId(Integer sysParamId) {
        this.sysParamId = sysParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_param.sys_param_name
     *
     * @return the value of t_sys_param.sys_param_name
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public String getSysParamName() {
        return sysParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_param.sys_param_name
     *
     * @param sysParamName the value for t_sys_param.sys_param_name
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public void setSysParamName(String sysParamName) {
        this.sysParamName = sysParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_param.sys_param_value
     *
     * @return the value of t_sys_param.sys_param_value
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public String getSysParamValue() {
        return sysParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_param.sys_param_value
     *
     * @param sysParamValue the value for t_sys_param.sys_param_value
     *
     * @mbggenerated Thu May 07 15:30:45 CST 2015
     */
    public void setSysParamValue(String sysParamValue) {
        this.sysParamValue = sysParamValue;
    }
}